import PDFDocument from "pdfkit";
import { marked } from "marked";
import type PDFKit from "pdfkit";

type Meta = {
  title: string;
  status?: string | null;
  updatedAt?: Date | null;
  author?: string | null;
};

function collectBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

function safeText(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function drawHeader(doc: PDFKit.PDFDocument, meta: Meta) {
  const title = meta.title || "Security Advisory";
  doc
    .fillColor("#06b6d4")
    .font("Helvetica-Bold")
    .fontSize(22)
    .text(title, { align: "left" });

  doc.moveDown(0.4);

  const line: string[] = [];
  if (meta.status) line.push(String(meta.status).toUpperCase());
  if (meta.author) line.push(meta.author);
  if (meta.updatedAt) line.push(meta.updatedAt.toISOString().slice(0, 10));

  if (line.length) {
    doc
      .fillColor("#94a3b8")
      .font("Helvetica")
      .fontSize(10)
      .text(line.join(" · "), { align: "left" });
  }

  doc.moveDown(1.0);
  doc
    .strokeColor("#155e75")
    .lineWidth(1)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(1.0);
}

function drawFooter(doc: PDFKit.PDFDocument) {
  const bottom = doc.page.height - doc.page.margins.bottom + 10;
  doc
    .strokeColor("#0b1220")
    .lineWidth(1)
    .moveTo(doc.page.margins.left, bottom)
    .lineTo(doc.page.width - doc.page.margins.right, bottom)
    .stroke();

  doc
    .fillColor("#64748b")
    .font("Helvetica")
    .fontSize(9)
    .text("Generated by SecHub", doc.page.margins.left, bottom + 6, {
      align: "left",
    });
}

function renderMarkdownTokens(doc: PDFKit.PDFDocument, markdown: string) {
  const tokens = marked.lexer(markdown ?? "");

  const bodyColor = "#cbd5e1";
  const headingColor = "#e2e8f0";
  const accentColor = "#22d3ee";

  const para = (t: string) => {
    const text = t.trim();
    if (!text) return;
    doc
      .fillColor(bodyColor)
      .font("Helvetica")
      .fontSize(11)
      .text(text, { lineGap: 3 });
    doc.moveDown(0.6);
  };

  const heading = (t: string, level: number) => {
    const size = level === 1 ? 18 : level === 2 ? 14 : 12;
    doc
      .fillColor(headingColor)
      .font("Helvetica-Bold")
      .fontSize(size)
      .text(t.trim(), { lineGap: 2 });
    doc.moveDown(0.4);
    if (level <= 2) {
      doc
        .strokeColor("#155e75")
        .lineWidth(0.5)
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .stroke();
      doc.moveDown(0.8);
    }
  };

  const bullet = (items: string[]) => {
    doc.fillColor(bodyColor).font("Helvetica").fontSize(11);
    for (const it of items) {
      const text = it.trim();
      if (!text) continue;
      doc.fillColor(accentColor).text("•", { continued: true });
      doc.fillColor(bodyColor).text(` ${text}`, { lineGap: 3 });
    }
    doc.moveDown(0.6);
  };

  const codeBlock = (code: string) => {
    const x = doc.page.margins.left;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const startY = doc.y;

    doc
      .save()
      .fillColor("#071018")
      .roundedRect(x, startY, width, 10, 6)
      .fill()
      .restore();

    doc
      .fillColor("#a5f3fc")
      .font("Courier")
      .fontSize(9.5)
      .text(code.replace(/\t/g, "  "), x + 10, startY + 8, {
        width: width - 20,
        lineGap: 2,
      });

    doc.moveDown(0.8);
  };

  const quote = (t: string) => {
    const x = doc.page.margins.left;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const startY = doc.y;

    doc
      .save()
      .fillColor("#06161f")
      .roundedRect(x, startY, width, 10, 6)
      .fill()
      .restore();

    doc
      .fillColor("#bae6fd")
      .font("Helvetica-Oblique")
      .fontSize(10.5)
      .text(t.trim(), x + 12, startY + 8, { width: width - 24, lineGap: 3 });

    doc.moveDown(0.8);
  };

  // Flatten common token shapes from marked.
  for (const tok of tokens) {
    if (tok.type === "space") continue;

    if (tok.type === "heading") {
      heading(safeText((tok as any).text), (tok as any).depth ?? 2);
      continue;
    }

    if (tok.type === "paragraph") {
      para(safeText((tok as any).text));
      continue;
    }

    if (tok.type === "blockquote") {
      const inner = (tok as any).tokens ?? [];
      const text = inner
        .map((t: any) => safeText(t.text))
        .filter(Boolean)
        .join("\n");
      quote(text || safeText((tok as any).text));
      continue;
    }

    if (tok.type === "list") {
      const items = ((tok as any).items ?? [])
        .map((it: any) => safeText(it.text))
        .filter(Boolean);
      bullet(items);
      continue;
    }

    if (tok.type === "code") {
      codeBlock(safeText((tok as any).text));
      continue;
    }

    if (tok.type === "hr") {
      doc
        .strokeColor("#155e75")
        .lineWidth(0.5)
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .stroke();
      doc.moveDown(1);
      continue;
    }

    // Fallback
    const text = safeText((tok as any).text) || safeText((tok as any).raw);
    if (text) para(text);
  }
}

export async function renderAdvisoryPdf(args: {
  meta: Meta;
  markdown: string;
}): Promise<Buffer> {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 56, bottom: 56, left: 54, right: 54 },
    info: {
      Title: args.meta.title,
      Producer: "SecHub",
      Creator: "SecHub",
    },
  });

  const bufPromise = collectBuffer(doc);

  drawHeader(doc, args.meta);
  renderMarkdownTokens(doc, args.markdown);
  drawFooter(doc);

  doc.end();
  return bufPromise;
}

