"use client";

import { format } from "date-fns";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { cleanAdvisoryMarkdown, stripLeadingMarkdownTitle } from "@/lib/advisory/markdown";
import { AI_SUMMARY_MODE_LABELS, AISummaryMode, FormData, getClassificationBanner } from "@/lib/advisory/template";
import { cn } from "@/lib/utils";

export function AdvisoryPreview({
  title,
  content,
  formData,
  templateName,
  summaryMode,
  linkedCount = 0,
  className,
}: {
  title: string;
  content: string;
  formData?: FormData;
  templateName?: string;
  summaryMode?: AISummaryMode | string | null;
  linkedCount?: number;
  className?: string;
}) {
  const markdown = stripLeadingMarkdownTitle(cleanAdvisoryMarkdown(content));
  const classification = formData ? getClassificationBanner(formData) : "TLP:AMBER — INTERNAL USE ONLY";
  const modeLabel =
    summaryMode && summaryMode in AI_SUMMARY_MODE_LABELS
      ? AI_SUMMARY_MODE_LABELS[summaryMode as AISummaryMode]
      : null;

  return (
    <article
      className={cn(
        "advisory-preview relative overflow-hidden rounded-sm border border-cyan-500/25 bg-gradient-to-br from-cyan-950/30 via-card/95 to-card/90",
        className
      )}
    >
      <span className="cyber-corner-tl" />
      <span className="cyber-corner-br" />

      {/* Classification banner */}
      <div className="border-b border-amber-500/30 bg-amber-950/40 px-4 py-2 text-center sm:px-8">
        <p className="font-mono-cyber text-[10px] font-bold uppercase tracking-[0.25em] text-amber-400">
          {classification}
        </p>
      </div>

      {/* Branded header */}
      <header className="border-b border-cyan-500/15 px-4 py-5 sm:px-8 sm:py-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-sm bg-cyan-900/60 ring-1 ring-cyan-500/30">
              <span className="font-display text-lg font-bold text-cyan-400">S</span>
            </div>
            <div>
              <p className="font-display text-sm font-semibold tracking-wide text-cyan-100">SecHub</p>
              <p className="font-mono-cyber text-[10px] text-cyan-500/70">Powered by Bramhashiv AI</p>
            </div>
          </div>
          <div className="text-right font-mono-cyber text-[10px] uppercase tracking-wider text-muted-foreground">
            <p>Security Advisory</p>
            <p>{format(new Date(), "PPP")}</p>
          </div>
        </div>

        <div className="mt-5 flex flex-wrap gap-2">
          {templateName && (
            <span className="rounded-sm border border-cyan-500/30 bg-cyan-950/50 px-2.5 py-0.5 font-mono-cyber text-[10px] uppercase tracking-widest text-cyan-400/90">
              {templateName}
            </span>
          )}
          {modeLabel && (
            <span className="rounded-sm border border-violet-500/30 bg-violet-950/40 px-2.5 py-0.5 font-mono-cyber text-[10px] uppercase tracking-widest text-violet-300/90">
              {modeLabel}
            </span>
          )}
          {linkedCount > 0 && (
            <span className="rounded-sm border border-emerald-500/30 bg-emerald-950/30 px-2.5 py-0.5 font-mono-cyber text-[10px] uppercase tracking-widest text-emerald-400/90">
              {linkedCount} source{linkedCount > 1 ? "s" : ""} merged
            </span>
          )}
        </div>

        {title && (
          <h1 className="mt-4 font-display text-xl font-bold leading-tight tracking-wide text-cyan-50 sm:text-2xl">
            {title}
          </h1>
        )}
      </header>

      {/* Rendered markdown body */}
      <div className="advisory-preview-body px-4 py-6 sm:px-8 sm:py-8">
        <div className="prose-advisory max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
        </div>
      </div>

      <footer className="border-t border-cyan-500/10 bg-cyan-950/20 px-4 py-3 sm:px-8">
        <p className="font-mono-cyber text-[10px] text-muted-foreground">
          Generated by SecHub · Bramhashiv AI · {format(new Date(), "yyyy-MM-dd HH:mm")} UTC
        </p>
      </footer>
    </article>
  );
}

/** @deprecated Use AdvisoryPreview */
export function MarkdownPreview({
  content,
  title,
  formData,
}: {
  content: string;
  title?: string;
  formData?: FormData;
}) {
  return (
    <AdvisoryPreview
      title={title ?? "Security Advisory"}
      content={content}
      formData={formData}
    />
  );
}
